// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using denizen_generator.Data;

#nullable disable

namespace denizen_generator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("denizen_generator.Models.Denizen", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("BirthDate")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "birth_date");

                    b.Property<string>("BloodType")
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "blood_type");

                    b.Property<string>("EyeColor")
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "eye_color");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "gender");

                    b.Property<string>("HairColor")
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "hair_color");

                    b.Property<string>("Handedness")
                        .HasColumnType("varchar(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "handedness");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "last_name");

                    b.Property<string>("SkinColor")
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("Relational:JsonPropertyName", "skin_color");

                    b.HasKey("Id");

                    b.ToTable("tbldenizen");
                });
#pragma warning restore 612, 618
        }
    }
}
